services:
  api:
    build: .
    container_name: org_structure_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/org_structure
      TEST_DATABASE_URL: postgresql+psycopg2://postgres:postgres@test_db:5432/org_structure_test
    depends_on:
      db:
        condition: service_healthy
      test_db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: postgres:16
    container_name: org_structure_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: org_structure
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d org_structure"]
      interval: 5s
      timeout: 5s
      retries: 10

  test_db:
    image: postgres:16
    container_name: org_structure_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: org_structure_test
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d org_structure_test"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  test_postgres_data: